name: CI

on: [push, pull_request]

env:
  MAVEN_ARGS: >-
    -V -B --no-transfer-progress
    -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  linux_maven:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17, 21]
    name: 'Linux JDK ${{ matrix.java }} Maven'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: 'Test'
        run: ./mvnw ${MAVEN_ARGS} -U clean verify
  linux_gradle:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17, 21]
    name: 'Linux JDK ${{ matrix.java }} Gradle'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: 'Test'
        run: ./gradlew buildAll
  windows_maven:
    name: 'Windows'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - name: 'Test'
        run: ./mvnw ${MAVEN_ARGS} -U clean verify
  mac_maven:
    name: 'Mac OS'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - name: 'Test'
        run: ./mvnw ${MAVEN_ARGS} -U clean verify
  linux_bazel:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17, 21]
    name: 'Linux JDK ${{ matrix.java }} Bazel'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - name: Test
        run: bazelisk test //...
      - name: Build
        run: bazelisk build //...
